# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('link-wifi', ['core', 'propagation', 'mobility'])
    module.source = [
        'model/link-wifi.cc',
        'helper/link-wifi-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('link-wifi')
    module_test.source = [
        'test/link-wifi-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'link-wifi'
    headers.source = [
        'model/link-wifi.h',
        'helper/link-wifi-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

