# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('yanci', ['network', 'internet'])
    module.includes = '.'
    module.source = [
		'model/yanci-header.cc',
		'model/yanci-hash.cc',
		'model/yanci-neighbor.cc',
		'model/yanci-queue.cc',
		'model/yanci-packet-info.cc',
		'model/yanci-protocol.cc',
		'model/yanci-packet-pool.cc',
		'model/yanci-device.cc',
		'helper/yanci-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'yanci'
    headers.source = [
		'model/yanci-header.h',
		'model/yanci-hash.h',
		'model/yanci-neighbor.h',
		'model/yanci-queue.h',
		'model/yanci-packet-info.h',
		'model/yanci-protocol.h',
		'model/yanci-packet-pool.h',
		'model/yanci-device.h',
		'helper/yanci-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

