# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('yanci-24', ['mobility', 'wifi', 'applications','yanci'])
    obj.source = 'yanci-24.cc'
    obj = bld.create_ns3_program('yanci-aodv', ['aodv','mobility', 'wifi', 'applications','yanci'])
    obj.source = 'yanci-aodv.cc'
